### ISSUE TITLE
RunTimeException?

### ISSUE THREAD

**Issue by aarowye** [Decencies/LunarRemapper#10]
C:\Users\Aarow\.lunarclient>java -jar lunar-remapper-1.0-SNAPSHOT.jar
@@@@@@@@@@@@@@@@@==@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@==-------=@@@@@@@@@@@@@
@@@@@@@@@@=-----@@@@@@=---=@@@@@@@@@
@@@@@@@@= -=@-  @=@@@@@@@@- @@@@@@@@         Lunar Remapper
@@@@@@@@- @@    =@@@@@@@=@= =@@@@@@@         Version: 1.0-SNAPSHOT
@@@@@@@@- @@     -=@=@@@=@= =@@@@@@@         Developed by Decencies
@@@@@@@@- @=@-         -@@= =@@@@@@@
@@@@@@@@- -               - -@@@@@@@
@@@@@@@@@@===---     -=-===@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[23:44:06] [main/INFO]: Loading Lunar Client for Minecraft 1.7.10.
[23:44:07] [main/INFO]: Loaded OptiFine version OptiFine_1.7.10_HD_U_E7.
Patching Classes 100% ←[33m???????????????????←[0m 1803/1803 (0:00:06 / 0:00:00)
Resolving Classes   0% ←[33m?                ?←[0m    1/1803 (0:00:00 / 0:00:10) java.lang.RuntimeException: Could not resolve name of class...
        at club.decencies.remapper.lunar.pipeline.mixin.MixinClassProcessor.lambda$process$1(MixinClassProcessor.java:97)
        at java.util.Optional.orElseThrow(Unknown Source)
        at club.decencies.remapper.lunar.pipeline.mixin.MixinClassProcessor.process(MixinClassProcessor.java:97)
        at club.decencies.remapper.lunar.Main.lambda$null$9(Main.java:328)
        at java.util.Optional.ifPresent(Unknown Source)
        at club.decencies.remapper.lunar.Main.lambda$null$10(Main.java:327)
        at java.lang.Iterable.forEach(Unknown Source)
        at club.decencies.remapper.lunar.Main.lambda$main$12(Main.java:324)
        at java.util.ArrayList.forEach(Unknown Source)
        at club.decencies.remapper.lunar.Main.main(Main.java:66)

If someone can help, i would appreciate it!

**Comment by Decencies** [comment]
Looks like your searge mapping file does not contain a mapping for a class.

If you would like more information, please pull the latest version, I have updated it to log the missing class mapping name.
