### ISSUE TITLE
Where I can find the mappings for 1.8.9?

### ISSUE THREAD

**Issue by Dani-error** [Decencies/LunarRemapper#6]

**Comment by Dani-error** [comment]
I think I have invalid mappings...

Logs:

```
[09:50:22] [main/INFO]: Loaded OptiFine version OptiFine_1.8.9_HD_U_M6_pre2.
[09:50:23] [main/INFO]: Loading Lunar Client for Minecraft 1.8.9.
Patching Classes 100% │█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████│ 2507/2507 (0:00:02 / 0:00:00) 
[HANDLER] Merged method net/minecraft/v1_8/hsspapesaespeasapashpaphh.handler$zzc000$onLoadTextureAtlas(Lnet/minecraft/v1_8/hhashhhahsppspspaseaaspss;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;ILnet/minecraft/v1_8/pphaepshsaepeehhhshhseehe;IILjava/util/Iterator;Ljava/util/Map$Entry;Lnet/minecraft/v1_8/sahsphheehsaeeeehhssahehs;Lnet/minecraft/v1_8/ahahheepheseepaphppaappas;Lnet/minecraft/v1_8/ahahheepheseepaphppaappas;Lnet/minecraft/v1_8/spehssshepaseshpaphseesha;[Ljava/awt/image/BufferedImage;)V does not have any callers.
	Mixin Handler Method: onLoadTextureAtlas(Lnet/minecraft/v1_8/hhashhhahsppspspaseaaspss;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;ILnet/minecraft/v1_8/pphaepshsaepeehhhshhseehe;IILjava/util/Iterator;Ljava/util/Map$Entry;Lnet/minecraft/v1_8/sahsphheehsaeeeehhssahehs;Lnet/minecraft/v1_8/ahahheepheseepaphppaappas;Lnet/minecraft/v1_8/ahahheepheseepaphppaappas;Lnet/minecraft/v1_8/spehssshepaseshpaphseesha;[Ljava/awt/image/BufferedImage;)V
[REDIRECT] Merged method net/minecraft/v1_8/spaeppheheaesehshshhheeep.redirect$zzf000$impl$renderModelAmbientOcclusionQuads$hasTintIndex(Lnet/minecraft/v1_8/hpaaehsaeaahasphaesaapahe;Lnet/minecraft/v1_8/psheeeeasaapehheaehhahahp;Lnet/minecraft/v1_8/heshesaappaphspessepsehsa;)Z does not have any callers.
	Mixin Redirect Method: impl$renderModelAmbientOcclusionQuads$hasTintIndex(Lnet/minecraft/v1_8/hpaaehsaeaahasphaesaapahe;Lnet/minecraft/v1_8/psheeeeasaapehheaehhahahp;Lnet/minecraft/v1_8/heshesaappaphspessepsehsa;)Z
[REDIRECT] Merged method net/minecraft/v1_8/spaeppheheaesehshshhheeep.redirect$zzf000$impl$renderModelStandardQuads$hasTintIndex(Lnet/minecraft/v1_8/hpaaehsaeaahasphaesaapahe;Lnet/minecraft/v1_8/psheeeeasaapehheaehhahahp;Lnet/minecraft/v1_8/heshesaappaphspessepsehsa;)Z does not have any callers.
	Mixin Redirect Method: impl$renderModelStandardQuads$hasTintIndex(Lnet/minecraft/v1_8/hpaaehsaeaahasphaesaapahe;Lnet/minecraft/v1_8/psheeeeasaapehheaehhahahp;Lnet/minecraft/v1_8/heshesaappaphspessepsehsa;)Z
Critical error finding original proxy method...
[REDIRECT] Merged method net/minecraft/v1_8/pshhaapsheshheahpsehsesss.redirect$zde000$impl$onRenderStringAtPos(Lnet/minecraft/v1_8/pshhaapsheshheahpsehsesss;Ljava/lang/String;ZLjava/lang/String;FFIZ)V does not have any callers.
	Mixin Redirect Method: impl$onRenderStringAtPos(Lnet/minecraft/v1_8/pshhaapsheshheahpsehsesss;Ljava/lang/String;ZLjava/lang/String;FFIZ)V
[HANDLER] Merged method net/minecraft/v1_8/ahhespsshahshppasspppehpp.handler$zei000$impl$onShouldShowName(Lnet/minecraft/v1_8/peeppeppahphhepheeshepshe;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V does not have any callers.
	Mixin Handler Method: impl$onShouldShowName(Lnet/minecraft/v1_8/peeppeppahphhepheeshepshe;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V
Critical error finding original proxy method...
Resolving Classes 100% │████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████│ 2507/2507 (0:00:00 / 0:00:00) 
Could not find nested field member aeseppaasaspahshaaheeasea from lunar/gS/lIIlIllllIlIIllIllllllIlI.
Could not find nested field member ehpeaapssapehpeppaaaspass from lunar/gS/lIIlIllllIlIIllIllllllIlI.
Could not find nested method member apshaahassahapapehaaspaae from lunar/gS/lIIlIllllIlIIllIllllllIlI.
Could not find nested field member aassheaasppphphphahahasah from lunar/gS/lIIlIllllIlIIllIllllllIlI.
Could not find nested field member aassheaasppphphphahahasah from lunar/gS/lIIlIllllIlIIllIllllllIlI.
Could not find nested field member aassheaasppphphphahahasah from lunar/gS/lIIlIllllIlIIllIllllllIlI.
Could not find nested field member sepepshaaaasapsasahsespae from lunar/gS/lIIlIllllIlIIllIllllllIlI.
Could not find nested field member hahhsasahpsshsshspshaaaah from lunar/gS/lIIlIllllIlIIllIllllllIlI.
Could not find nested field member sepepshaaaasapsasahsespae from lunar/gS/lIIlIllllIlIIllIllllllIlI.
Could not find nested field member aeseppaasaspahshaaheeasea from lunar/gS/lIIlIllllIlIIllIllllllIlI.
Could not find nested field member hahhsasahpsshsshspshaaaah from lunar/gS/lIIlIllllIlIIllIllllllIlI.
Could not find nested field member ehpeaapssapehpeppaaaspass from lunar/gS/lIIlIllllIlIIllIllllllIlI.
Could not find nested field member aeaahpaphahseeeehpsesshaa from lunar/gS/lIIlIllllIlIIllIllllllIlI.
Could not find nested field member aeaahpaphahseeeehpsesshaa from lunar/gS/lIIlIllllIlIIllIllllllIlI.
Could not find nested field member aeaahpaphahseeeehpsesshaa from lunar/gS/lIIlIllllIlIIllIllllllIlI.
Could not find nested field member aassheaasppphphphahahasah from lunar/gS/lIIlIllllIlIIllIllllllIlI.
true
pesapeeaaehpashahappsepaa
java.lang.RuntimeException: Could not map a minecraft method from avn. (index out of bounds, 45)
	at club.decencies.remapper.lunar.pipeline.TransformationMappings.unmapInheritedMethodMemberName(TransformationMappings.java:216)
	at club.decencies.remapper.lunar.pipeline.TransformationMappings.mapMethodName(TransformationMappings.java:140)
	at org.objectweb.asm.commons.MethodRemapper.visitMethodInsn(MethodRemapper.java:169)
	at org.objectweb.asm.tree.MethodInsnNode.accept(MethodInsnNode.java:115)
	at org.objectweb.asm.tree.InsnList.accept(InsnList.java:144)
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:751)
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:649)
	at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:452)
	at club.decencies.remapper.lunar.Main.lambda$main$12(Main.java:349)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at club.decencies.remapper.lunar.Main.main(Main.java:66)

```

**Comment by rastiqdev** [comment]
I have the same issue but Decencies told me on Discord that he’ll try to fix that later

**Comment by Dani-error** [comment]
Im using only the .srg file, because if I use the tool with the fields, param, methods.csv crashes.

Log:

```
Exception in thread "main" java.lang.NullPointerException
	at club.decencies.remapper.lunar.Main.lambda$main$0(Main.java:59)
	at club.decencies.remapper.lunar.util.FileUtil.walk(FileUtil.java:21)
	at club.decencies.remapper.lunar.Main.main(Main.java:49)
```

**Comment by TheKodeToad** [comment]
I reported that
I think it's a Linux-specific issue
