### ISSUE TITLE
Keep giving optifine error even if already downloaded

### ISSUE THREAD

**Issue by mrcorpz** [Decencies/LunarRemapper#8]
Even if optifine is already downloaded, it still will not work

![image](https://user-images.githubusercontent.com/79889814/154648896-2b578250-05fa-421b-9385-8deac75dd3e2.png)

Extra Info

Using Zulu JDKFX 16

ERROR LOG
 
@@@@@@@@@@@@@@@@@==@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@==-------=@@@@@@@@@@@@@
@@@@@@@@@@=-----@@@@@@=---=@@@@@@@@@
@@@@@@@@= -=@-  @=@@@@@@@@- @@@@@@@@         Lunar Remapper
@@@@@@@@- @@    =@@@@@@@=@= =@@@@@@@         Version: 1.0-SNAPSHOT
@@@@@@@@- @@     -=@=@@@=@= =@@@@@@@         Developed by Decencies
@@@@@@@@- @=@-         -@@= =@@@@@@@
@@@@@@@@- -               - -@@@@@@@
@@@@@@@@@@===---     -=-===@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
preview_https://optifine.net/downloadx?f=preview_OptiFine_1.8.9_HD_U_M6_pre2.jar&x=470917a35025c9d02a548dcb377a84ec
java.net.MalformedURLException: no protocol: preview_https://optifine.net/downloadx?f=preview_OptiFine_1.8.9_HD_U_M6_pre2.jar&x=470917a35025c9d02a548dcb377a84ec
        at java.base/java.net.URL.<init>(URL.java:674)
        at java.base/java.net.URL.<init>(URL.java:569)
        at java.base/java.net.URL.<init>(URL.java:516)
        at club.decencies.remapper.lunar.util.OptiFineDownloader.download(OptiFineDownloader.java:34)
        at club.decencies.remapper.lunar.util.OptiFineDownloader.download(OptiFineDownloader.java:50)
        at club.decencies.remapper.lunar.Main.lambda$main$6(Main.java:83)
        at java.base/java.util.Optional.ifPresent(Optional.java:178)
        at club.decencies.remapper.lunar.Main.lambda$main$12(Main.java:82)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at club.decencies.remapper.lunar.Main.main(Main.java:66)

**Comment by Dani-error** [comment]
remove the "preview_" in the file name!

**Comment by Decencies** [comment]
I will make the OptiFine download system smarter when I refactor the code base, thanks for pointing this out!
